ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.wellness_library ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.couples_challenges ENABLE ROW LEVEL SECURITY;