// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pojykfjbtmpsvdkyhxbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvanlrZmpidG1wc3Zka3loeGJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NTc2MjUsImV4cCI6MjA4NTIzMzYyNX0.4DaQsaKOucZ49cw32ZWaKMl5igTSQjQDaYTqlplFEvE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);