// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://aqwuhkrxqxaoaxapafmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxd3Voa3J4cXhhb2F4YXBhZm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NDAyNjcsImV4cCI6MjA4NTMxNjI2N30.JXA17OYjFTOmBdcKLKKFtYCZgagQD-funfC9mj1PA98";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);